run:
  timeout: 5m
  modules-download-mode: readonly

linters:
  enable:
    - gosimple
    - ineffassign
    - staticcheck
    - copyloopvar
    - errname
    - unconvert

linters-settings:
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
